name: Build React App
run-name: ${{ github.actor }} Building their react app
on: [push]
jobs:
  # Explore-GitHub-Actions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  #     - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  #     - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
  #     - name: List files in the repository
  #       run: |
  #         ls ${{ github.workspace }}
      
  #     - run: echo "🍏 This job's status is ${{ job.status }}."
  
  # testing:
  #   runs-on: ubuntu-latest

  # build: 
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #     - run: cd github_actions_playin && npm install && npm run build --if-present
  #     - run: command -v git

  deploy: 
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: pwd;ls;command -v git

      # - run: | 
      #     cd /tmp &&
      #     git clone https://yeltnar:${{ secrets.GITHUB_TOKEN }}@github.com/yeltnar/github_actions_playin.git


      - run: |
          cd github_actions_playin && 
          npm install && 
          npm run build --if-present && 
          mv build ../docs &&
          cd ..
      - run: pwd;ls;command -v git
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3        
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      - run : |
          echo ${{ secrets.GITHUB_TOKEN }}
      - run: |
          pwd; ls; 
          git config --global user.email "github-actions@andbrant.com" && 
          git config --global user.name "Drew Bot" &&
          rm -rf github_actions_playin &&
          git add . &&
          find . | awk '!/node_modules/{print $0}' | awk '!/\.git/{print}' &&
          git commit -m 'auto build' &&
          git remote remove origin && 
          git remote add origin https://yeltnar:${{ secrets.GITHUB_TOKEN }}@github.com/yeltnar/github_actions_playin.git &&
          git checkout -b gh-pages && 
          git push -fu origin gh-pages